### ISSUE TITLE
Warning. Invalid resolution 0 dpi. Using 70 instead.

### ISSUE THREAD

**Issue by ojnc** [FlorianKoerner/compiled-tesseract#4]
On Linux Ubuntu 16.04 everything fine apart for a Warning message

**Warning. Invalid resolution 0 dpi. Using 70 instead.**

The files checked were all 300dpi;
quality seems to be unimpaired

**Comment by FlorianKoerner** [comment]
See: https://github.com/tesseract-ocr/tesseract/search?q=%22Invalid+resolution+0+dpi.+Using+70+instead.%22&unscoped_q=%22Invalid+resolution+0+dpi.+Using+70+instead.%22&type=Issues

**Comment by ojnc** [comment]
Thanks!
I realize now opencv pre-processing had changed DPI
